--- #playbook.yml
- hosts: dev
  user: ansible
  connection: ssh
  become: yes

  tasks:
    - name: install apache
      action: yum pkg=httpd state=present
    - name: index-deploy
      action: copy src=index.html dest=/var/www/html
    - name: service start
      command: service httpd start
